name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Clone repo
        uses: actions/checkout@v3.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          distribution: termurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apk-debug
        uses: eskatos/gradle-command-action@v2.3.2
        with:
          arguments: assembleDebug
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload apk-debug
        uses: actions/upload-artifact@v3
        if: ${{ !github.head_ref }}
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

